
all: advent3_1.run advent3_2.run

advent3_1.run: advent3_1.adb
	gnatmake advent3_1.adb -o advent3_1.run

advent3_2.run: advent3_2.adb
	gnatmake advent3_2.adb -o advent3_2.run

run1: advent3_1.run
	@./advent3_1.run

run2: advent3_2.run
	@./advent3_2.run
